config/routes.rb
Rails.application.routes.draw do
  get '/404' => 'errors#not_found', as: 'not_found'

  root 'documents#new'

  get '/' => 'documents#new'
  post '/' => 'documents#create', as: 'document'
  get '/:token' => 'documents#show', as: 'document_show'
  delete '/:token' => 'documents#destroy', as: 'document_destroy'

end

app/models/document.rb
class Document < ActiveRecord::Base
  before_save :encrypt_content
  before_save :set_friendly_id
  before_save :set_expired_at

  attr_accessor :password

  validates :content, presence: true

  def self.find_and_validate_by_friendly_id(friendly_id)
    document = self.find_by(friendly_id: friendly_id)

    # not found
    if document.nil?
      return nil
    end

    # one time document or expired
    if document.is_expired?
      return process_expired(document)
    end

    return document
  end

  def content_decrypted
    encryption =Cryptor.new(encrypted_content: self.content, password: @password)
    return encryption.decrypt()
  end

  def is_expired?
    expire = self.expired_at

    case expire
    when "0", nil, 0
      # One time link
      return true

    when "-1", -1
      # immortal link
      return false

    else
      # check period
      expire = expire.to_datetime rescue false

      if not expire
        Rails.logger.error "Parse document expire fail"
        return true
      end

      if Time.now <= expire
        return false
      end

      if Time.now > expire
        return true
      end

      return true
    end
  end

  private
  def encrypt_content
    encryption =Cryptor.new(content: self.content)
    # This is random password from Cryptor
    @password = encryption.password
    self.content = encryption.encrypt()
  end

  def set_friendly_id
    self.friendly_id = _gen_unique_friendly_id
  end

  def set_expired_at
    self.expired_at = _get_datetime_from_duration_string
  end

  def _gen_unique_friendly_id
    all_doc = Document.all.as_json
    begin
      uniq_id = SecureRandom.uuid[0..4]
      is_id_exist = ((all_doc.select {|v| v['friendly_id'] == uniq_id}) != [])
    end while is_id_exist

    return uniq_id
  end

  def _get_datetime_from_duration_string
    case self.expired_at
    when 0, '0', nil
      return 0
    when '-1', -1
      return -1
    else
      return Time.now + self.expired_at.to_i.seconds
    end
  end

  # Cloning object and deteling expired doc
  def self.process_expired(document)
    # document_clone is not persistence data
    document_clone = document.clone
    Thread.new {
      document.destroy rescue Rails.logger.info "Delete document fail"
    }
    return document_clone
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :destroy]
  skip_before_filter :verify_authenticity_token, :only => [:create]

  rescue_from OpenSSL::Cipher::CipherError do |exception|
    message = "Decrypt fail #{params}"
    Rails.logger.error message
    redirect_to not_found_url
  end

  def show
    respond_to do |format|
      format.html {}
      format.json {

      }
      format.raw {
        render plain: @document.content_decrypted, content_type: 'text/plain'
      }
    end
  end

  def new
    @document = Document.new
  end

  def create
    @document = Document.new(document_params)

    @res = {
      message: [],
      uri: ''
    }

    respond_to do |format|
      if @document.save
        token = TokenService.build(friendly_id: @document.friendly_id, password: @document.password)
        @res[:uri] = request.base_url + request.original_fullpath + token
        res_status = 201
      else
        @res[:message] = @document.errors.full_messages
        res_status = 400
      end

      format.json { render :new, status: res_status }
      format.html {render json: @res, status: res_status}
    end
  end

  def destroy
    @res = {
      error: '',
      status: 204
    }

    if not @document.destroy
      @res[:error] = 'Could not delete'
      @res[:status] = 400
    end

    respond_to do |format|
      format.json { render json: @res, status: @res[:status] }
      format.js {}
    end
  end

  private
    def set_document
      token = TokenService.extract(token: params[:token])
      @document = Document.find_and_validate_by_friendly_id(token[:friendly_id])

      if @document.nil?
        redirect_to not_found_url
        return
      end

      # Set password to decrypt
      @document.password = token[:password]
    end

    def document_params
      params.require(:document).permit(:content, :title, :syntax, :expired_at)
    end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(document_title)
    title = 'PikaBin - Your friendly and secure PasteBin'

    return title if params[:action] == 'new' or params[:controller] == 'errors'

    title = if document_title
      "#{document_title} | #{title}"
    end

    return title
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
  def syntax_dropdown
    content_tag :div, class: "menu" do
      ACE_MODE.each do |syntax|
        concat(content_tag :div, syntax, class: "item", :'data-value' => syntax)
      end
      ACE_MODE_ALIAS.each do |fake, real|
        concat(content_tag :div, fake, class: "item", :'data-value' => real)
      end
    end
  end

  def expired_at_dropdown
    content_tag :div, class: "menu" do
      EXPIRE.each do |short, duration|
        concat(content_tag :div, duration['text'], class: "item", :'data-value' =>  duration['value'])
      end
    end
  end

  def tabsize_dropdown
    content_tag :div, class: "menu" do
      [2, 4, 8].each do |size|
        concat(content_tag :div, size, class: "item", :'data-value' =>  size)
      end
    end
  end

  def print_document_title(document)
    if document
      return 'Unnamed document' if document.title.blank?
      return document.title
    end
  end

  def print_expired_at(document)
    expire = document.expired_at

    if expire == 0 or expire == '0' or expire.nil?
      return content_tag :div, class: "orange" do
        "Don't close this window, this document was removed"
      end
    end

    if expire == '-1'
      return content_tag :div, class: "" do
        "This document is immortal (:, you can delete it manually"
      end
    end

    begin
      return "This document will expire in <strong data-tooltip='#{expire}'>" \
      "<u>#{distance_of_time_in_words(Time.now, expire.to_datetime)}</u></strong>.".html_safe
    rescue Exception => e
    end
  end

  def load_syntax(document)
    if ACE_MODE_ALIAS[document.syntax].nil?
      document.syntax
    else
      ACE_MODE_ALIAS[document.syntax]
    end
  end
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/views/documents/destroy.js.erb
<% if @res[:error] == '' %>
$('#btn-destroy').html('<i class="checkmark icon"></i> Deleted');
$('#btn-destroy').attr('class', 'ui disabled green right floated button');
$('#btn-show-raw').remove();
<% else %>
alert('<%= @res[:error] %>');
<% end %>

app/views/documents/new.html.erb
<%= form_for @document, url: {action: "create"}, html: {class: "ui form"} do |f| %>
  <!-- text area -->
  <div class="field">
    <label>Paste your text here:</label>
    <div autofocus name="" id="editor"></div>
    <%= f.hidden_field(:content) %>
  </div>

  <%= content_tag :div, nil, class: ["divider", "divider30"] %>

  <!-- attributes -->
  <div class="ui grid">
    <!-- title -->
    <div class="four wide computer eight wide tablet sixteen wide mobile column">
      <%= f.label :title %>
      <%= f.text_field(:title) %>
    </div>

    <div class="four wide computer eight wide tablet sixteen wide mobile column">
      <%= f.label :expired_at %>
      <div class="ui">
        <div class="ui fluid normal selection dropdown dropdown-expired_at">
          <%= f.hidden_field(:expired_at, value: '0') %>
          <i class="dropdown icon"></i>
          <div class="default text">After reading</div>
          <%= expired_at_dropdown %>
        </div>
      </div>
    </div>

    <!-- syntax -->
    <div class="four wide computer eight wide tablet sixteen wide mobile column">
      <%= f.label :syntax %>
      <div class="ui">
        <div class="ui fluid search normal selection dropdown dropdown-syntax">
          <%= f.hidden_field(:syntax, value: 'plain') %>
          <i class="dropdown icon"></i>
          <div class="default text">Plain text</div>
          <%= syntax_dropdown %>
        </div>
      </div>
    </div>

    <!-- syntax -->
    <!-- <div class="four wide computer eight wide tablet sixteen wide mobile column">
      <%= label_tag(:tab, "Tab size:") %>
      <div class="ui">
        <div class="ui fluid search normal selection dropdown dropdown-tabsize">
          <i class="dropdown icon"></i>
          <div class="default text">2</div>
          <%= tabsize_dropdown %>
        </div>
      </div>
    </div> -->

  </div> <!-- end of attribute section -->

  <%= content_tag :div, nil, class: ["divider", "divider30"] %>
  <%= content_tag :div, nil, class: ["ui", "error", "message"] %>

  <%= button_tag(type: 'submit', class: 'ui button fluid teal') do %>
    Submit
  <% end %>

<% end %>
<!--  end of form -->

<div class="ui link_placeholder" style="display: none">
  <center>
    <h1>Your Link:</h1>
    <div class="ui action input">
      <input type="text" class="shared_link" value="" size="60">
      <button class="ui teal right labeled icon button button-copy" data-clipboard-target=".shared_link">
        <i class="copy icon"></i>
        Ctrl/⌘ + V
      </button>
    </div>
  </center>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.5.12/clipboard.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.3/ace.js" type="text/javascript" charset="utf-8"></script>

<script>
// Init editor
var editor = ace.edit("editor");
editor.setTheme("ace/theme/monokai");
editor.session.setOption("useWorker", false);
editor.getSession().setUseSoftTabs(true);
editor.getSession().setTabSize(2);
editor.setHighlightActiveLine(true);
editor.setOptions({
    maxLines: 40,
    minLines: 20
});

editor.focus();

new Clipboard('.button-copy');

// Assign value in editor to form input
editor.getSession().on("change", function(e){
  editorVal = editor.getValue();
  try {
    $('#document_content').val(editorVal);
  } catch(e){
    // Do smt if error
  }
})

// Set syntax
$('.dropdown-syntax').dropdown({
  action: 'activate',
  onChange: function(value, text, $choice) {
    editor.getSession().setMode("ace/mode/" + value);
    return;
  }
});

// Set expired_at
$('.dropdown-expired_at').dropdown();

// Define from validation rule
var validationRules = {
  content: {
    identifier  : 'document[content]',
    rules: [
      {
        type   : 'empty',
        prompt : 'Forgot your text'
      }
    ]
  }
}

// Form handle
$('.ui.form').form({
  on: 'submit',
  fields: validationRules,
  // When validation is successful
  onSuccess: function(event, fields){
    event.preventDefault();
    var myForm = $('.ui.form');
    var sbmButton = $('.ui.form .button');

    sbmButton.addClass('loading disabled');

    $.ajax({
      type: myForm.attr('method'),
      url: myForm.attr('action'),
      data: fields,
      dataType: 'json',
      statusCode: {
        201: function (data) {
          console.log(data)
          myForm.hide();
          $('.link_placeholder input').val(data.uri);
          $('.link_placeholder').show();
          $('.link_placeholder input').select();
        },
        400: function (data) {
          alert(data.message);
        },
        500: function (data) {
          alert('Server Error.');
        }
      }
    }).fail(function( data ) {
      // Do after failure
      console.log(data);
    }).always(function( data ) {
      // Always execute after ajax call done
      sbmButton.removeClass('loading disabled');
    });

    return false
  }
});

// Set button to copied when click
$('.button-copy').click(function(event){
  event.preventDefault();
  $(this).html('<i class="copy icon"></i> Copied');
});
</script>

app/views/documents/show.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.3/ace.js" type="text/javascript" charset="utf-8"></script>

<style>
h1 {
  margin-top: 0;
  margin-bottom: 5px;
}
</style>

<div class="ui grid">
  <div class="eight wide computer eight wide tablet sixteen wide mobile column">
    <h1 class=""><%= print_document_title(@document) %></h1>
    <p><%= print_expired_at(@document) %></p>
  </div>

  <div class="eight wide computer eight wide tablet sixteen wide mobile column">
    <%= if @document.expired_at.to_i != 0
      link_to '<div class="visible content"><i class="trash outline icon"></i> Delete now</div><div class="hidden content"><i class="trash outline icon"></i> Delete now</div>'.html_safe,
        document_destroy_path,
        class: "ui red basic right floated button vertical animated",
        id: 'btn-destroy',
        data: {
          remote: true, type: 'script', method: 'delete',
          confirm: 'Are you sure ?'
        }
      end %>
    <a id="btn-show-raw" class="ui vertical animated button right floated teal" target="_blank" href="<%= document_show_path(params[:token]) %>.raw">
      <div class="visible content">Raw</div>
      <div class="hidden content">
        Raw
      </div>
    </a>
  </div>
</div>

<div class="divider divider60"></div>

<div name="" id="readonly_editor"><%= @document.content_decrypted %></div>

<div class="divider divider60"></div>

<script type="text/javascript">
// Init editor
var editor = ace.edit("readonly_editor");
editor.session.setOption("useWorker", false);
editor.setTheme("ace/theme/monokai");
editor.getSession().setMode("ace/mode/<%= load_syntax(@document) %>");
editor.setOptions({
    maxLines: 1500,
    minLines: 20
});
editor.setReadOnly(true);
</script>

app/views/layouts/_footer.html.erb
<footer class="centered">
  PikaBin by <a href="mailto:dangtunglam14@gmail.com">LamDT</a>
  <br>
  <a href="https://github.com/tunglam14/pikabin" target="_blank" style="color: #000">
    <i class="icon large github alternate"></i>
  </a>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= page_title(print_document_title(@document)) %></title>

  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
  <meta name="author" content="PikaBin">
  <meta name="description" content="PikaBin is a website where you can store text online for a set period of time">

  <meta property="og:title" content="<%= page_title(print_document_title(@document)) %>" />
  <meta property="og:image" content="<%= asset_url('og_image.png') %>" />
  <meta property="og:type" content="article" />
  <meta property="og:url" content="<%= request.base_url + request.original_fullpath %>" />
  <meta property="og:image" content="<%= asset_url('og_image.png') %>" />
  <meta property="article:author" content="Mr. Nobody" />
  <% if @document and @document.title %>
  <meta property="og:article:expiration_time" content="<%= @document.expired_at %>" />
  <% end %>

  <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.min.js" %>
  <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/jquery-ujs/1.2.1/rails.min.js" %>
  <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.1/semantic.min.js" %>
  <%= javascript_include_tag 'application' %>

  <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.1/semantic.min.css" %>
  <%= stylesheet_link_tag    'application', media: 'all' %>

  <%= csrf_meta_tags %>
</head>
<body>
  <div class="ui grid">
    <div class="ten wide computer twelve wide column fourteen wide mobile column centered container">

      <div class="ui secondary pointing menu">
        <a class="active item" href="/">
          <i class="large icons">
            <i class="code icon"></i>
            <i class="inverted corner paste icon"></i>
          </i>
          PikaBin
          <!-- <i class="ui label">beta</i> -->
        </a>
        <div class="right menu">
        </div>
      </div>

      <div class="divider divider30"></div>

      <div class="main">
        <%= yield %>
      </div> <!--  end of .main -->

      <%= render 'layouts/footer' %>

    </div>
  </div>

  <script>
    // $('.dropdown').dropdown();
  </script>
</body>
</html>